# Generated by Django 5.2.11 on 2026-05-04 03:21

import secrets
import string

import events.models
from django.db import migrations, models


def generate_unique_event_code(Event):
    alphabet = string.ascii_uppercase + string.digits

    while True:
        code = "EVT-" + "".join(secrets.choice(alphabet) for _ in range(6))
        if not Event.objects.filter(event_code=code).exists():
            return code


def populate_event_codes(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    for event in Event.objects.filter(event_code__isnull=True):
        event.event_code = generate_unique_event_code(Event)
        event.save(update_fields=["event_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_code",
            field=models.CharField(
                max_length=20,
                null=True,
                blank=True,
                editable=False,
            ),
        ),
        migrations.RunPython(populate_event_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="event_code",
            field=models.CharField(
                default=events.models.generate_event_code,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]