# Generated by Django 5.2.11 on 2026-05-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private events are hidden from the public event list but accessible by registration link.'),
        ),
    ]
