# Generated by Django 5.2.11 on 2026-08-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventcloseout_eventattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='leave_cutoff_minutes',
            field=models.PositiveIntegerField(blank=True, choices=[(None, 'No cutoff'), (30, '30 minutes before'), (60, '60 minutes before'), (90, '90 minutes before'), (120, '120 minutes before'), (150, '150 minutes before'), (180, '180 minutes before')], help_text='Players cannot self-leave after this cutoff before kick-off.', null=True),
        ),
    ]
