# Generated by Django 5.2.11 on 2026-07-13 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_eventcloseout_eventattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('create_event', 'Create Event'), ('set_weekly_limit', 'Set Weekly Limit')], max_length=30)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly')], default='weekly', max_length=20)),
                ('run_day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('run_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('event_day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('amount_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('playing_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('waiting_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('backup_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('weekly_limit_enabled', models.BooleanField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_standing_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['run_day_of_week', 'run_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandingOrderRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('created_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standing_order_run_logs', to='events.event')),
                ('standing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='standing_orders.standingorder')),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
