# Generated by Django 5.2.11 on 2026-08-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standing_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingorder',
            name='leave_cutoff_minutes',
            field=models.PositiveIntegerField(blank=True, choices=[(None, 'No cutoff'), (30, '30 minutes before'), (60, '60 minutes before'), (90, '90 minutes before'), (120, '120 minutes before'), (150, '150 minutes before'), (180, '180 minutes before')], help_text='Events created by this standing order will lock self-leaving after this cutoff before kick-off.', null=True),
        ),
    ]
