# Generated by Django 5.2.11 on 2026-04-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
