# Generated by Django 5.2.11 on 2026-04-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('admin', 'Admin')], default='web', max_length=20),
        ),
    ]
