# Generated by Django 5.2.11 on 2026-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_playing_slots', models.PositiveIntegerField(default=15)),
                ('default_waiting_slots', models.PositiveIntegerField(default=5)),
                ('default_backup_slots', models.PositiveIntegerField(default=3)),
                ('default_location', models.CharField(blank=True, default='KHG', max_length=255)),
                ('default_amount_payable', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('default_start_time', models.TimeField(blank=True, null=True)),
                ('default_end_time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
