# Generated by Django 5.2.11 on 2026-04-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='default_amount_payable',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_location',
            field=models.CharField(blank=True, default='Keat Hong Gardens (Opposite BLK 815 CCK Ave 7)', max_length=255),
        ),
    ]
