# Generated by Django 5.2.11 on 2026-05-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_alter_systemsettings_default_amount_payable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='only_allow_once_per_week_registration',
            field=models.BooleanField(default=False),
        ),
    ]
